INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',0,1,0 FROM People,Movie WHERE pImdbId = 'nm0000338' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Don Vito Corleone',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0000008' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Michael Corleone',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0000199' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Sonny Corleone',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0001001' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Clemenza',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0144710' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Tom Hagen',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0000380' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Capt. McCluskey',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0001330' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Jack Woltz',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0549134' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Barzini',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0002017' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Sollozzo',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0504803' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Kay Adams',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0000473' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Tessio',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0001820' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Connie',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0001735' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Carlo',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0751625' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Fredo',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0001030' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Cuneo',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0094036' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Johnny Fontane',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0553887' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Mama Corleone',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0455088' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Luca Brasi',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0598926' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Paulie Gatto',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0553908' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Bonasera',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0181128' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Neri',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0109175' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Moe Greene',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0733678' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Bruno Tattaglia',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0320413' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Nazorine',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0780005' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Theresa Hagen',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0515372' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Philip Tattaglia',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0719353' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Lucy Mancini',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0512642' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Sandra Corleone',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0339589' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'Mrs. Clemenza',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0792132' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0292875' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0748665' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0263172' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0000065' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0932336' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0722000' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0957038' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0226544' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0247622' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0740407' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0851790' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0167428' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0809602' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0426895' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0504717' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0722504' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0004615' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0142301' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0210832' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0002859' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0105010' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0303031' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0450424' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0804490' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0895052' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0133945' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm4800791' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0768733' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0340311' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0628039' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0692446' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0063712' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm1349385' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0416097' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0493796' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0540454' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0064854' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0283166' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0518375' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0518394' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2868957' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0165343' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0130605' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0219873' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0962881' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0239619' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm4890574' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm1233439' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm4890698' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm4890740' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm4707065' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0974546' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0062656' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0117851' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0122437' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0197845' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0152469' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0124832' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0257308' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2102773' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0461422' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2099171' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0658562' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0703830' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm1661486' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2095737' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0758306' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0762376' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0821370' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0867347' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0901749' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0908617' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0911809' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2092615' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0003118' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0628096' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0701229' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm1287578' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2358858' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2889123' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0004555' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2451512' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0416097' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0490658' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0548772' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0770733' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0813400' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0923845' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0101110' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0109066' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0006274' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0287331' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0358415' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2482917' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0561729' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0757536' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm1641535' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0899164' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0367297' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2101217' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2103309' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0901735' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2092780' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2092473' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0058565' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0154693' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0394476' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0578864' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0957038' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0220221' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0316786' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0343780' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0421528' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0432921' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0500055' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2092032' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2093141' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0628115' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0754944' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0770733' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm4890834' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm1006702' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0169591' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0000338' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0005679' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm4890795' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2097523' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm4133112' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0493245' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0534268' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm1619997' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm4890707' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm1767419' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0710997' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm2845194' AND movieId = 2);
INSERT IGNORE INTO moviepeople(fkMovieId,fkPeopleId,castName,actorFlag,directorFlag,writerFlag) (SELECT movieId,peopleId,'',1,0,0 FROM People,Movie WHERE pImdbId = 'nm0932336' AND movieId = 2);
